name: Signals Worker
on:
  schedule:
    - cron: '0 * * * *'   # every hour
  workflow_dispatch: {}
concurrency:
  group: signals-worker
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run worker
        env:
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          LUNARCRUSH_KEY: ${{ secrets.LUNARCRUSH_KEY }}
          DUNE_KEY: ${{ secrets.DUNE_KEY }}
          DUNE_QUERY_ID: ${{ secrets.DUNE_QUERY_ID }}  
        run: python signals_worker.py
